Repository binaryninja11/weather, pull requests merged in 2025-01, with the labels that each got.

#14 Integrating
  requirements.txt
  src/app.py
  src/static/. .
  src/templates/. .
Labels: setup, backend

#19 Abduaziz proger
  requirements.txt
  src/app.py
  src/static/. .
  src/static/style.css
  src/templates/. .
  src/templates/index.html
Labels: setup, frontend

#21 Iosproger
  LICENSE
  README.md
  docs/_config.yml
  docs/index.md
  requirements.txt
  src/app.py
  src/static/. .
  src/static/style.css
  src/templates/. .
  src/templates/index.html
Labels: setup

#29 Update app.py
  src/app.py
Labels: backend

#30 Abduaziz proger
  src/app.py
  src/static/style.css
  src/templates/index.html
Labels: frontend

#33 Khikmatov0110
  design/IMAGE 2025-01-08 23:08:26.jpg
  design/IMAGE 2025-01-08 23:08:29.jpg
Labels: design

#42 Iosproger
  DEPLOYMENT.md
  requirements.txt
  src/app.py
Labels: teamlead

#50 Iosproger
  .devcontainer/devcontainer.json
  .dockerignore
  .github/workflows /deploy.yml
  Dockerfile
Labels: teamlead, deploy
